INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (1, '1.png', 100, 'Райское Наслаждение', 'Ваааау!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (2, '2.png', 150, 'Наполеон', 'Величественно.', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (3, '3.jpg', 130, 'Люди в Черном', 'Стирает память!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (4, '4.jpg', 180, 'Вечера на Хуторе Близ Диканьки', 'Это правда вкусно', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (5, '5.png', 90, 'Собачье Сердце', 'Ни одна собака не пострадала', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (6, '6.jpg', 120, 'Нотки Сомали', 'Белиссимо!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (7, '7.jpg', 100, 'Морозная Свежесть', 'Обморозительно!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (8, '8.png', 190, 'Растения Против Зомби', 'зонбительно', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (9, '9.jpg', 200, 'Автостопом по Галактике', 'Don`t Panic!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (10, '10.png', 120, 'Бедный Еврей', 'так мороженое называется', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (11, '11.jpg', 150, 'Вторжение с Нибиру', 'Жесть!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (12, '12.png', 250, 'Ирландский Слон', 'Вот это размер!', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (13, '13.jpg', 200, 'Терминатор 2', 'Hasta la vista, baby', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (14, '14.jpg', 190, 'Cadillac Escalade', 'Шава машина', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (15, '15.jpg', 60, 'Скромный десерт', 'Скромно, но стильно', 'Шаурма', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (16, 'burger.png', 150, 'Андрей Васильевич', 'Великан!', 'Бургер', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (17, 'pizza.jpg', 250, 'Солнечный диск', 'Вкуснотища!', 'Пицца', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (18, 'dener_1.png', 80, 'Дедушкин секрет', 'Невероятно!', 'Денер', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (19, 'фалафель_1.jpg', 130, 'Тройной биг тэйсти обед', 'Невозможно съесть полностью!', 'Фалафель', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (20, 'фалафель_2.png', 150, 'Глубокая Эйфория', 'Обалдеть', 'Фалафель', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (21, 'medovarus.jpg', 40, 'Винни Пух: Кровь и Мед', 'Страшно вкусно!', 'Напиток', 'Харам');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (22, 'baltika0.png', 40, 'Нестареющая классика', 'Кайф!', 'Напиток', 'Харам');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (23, 'hoooch.jpeg', 60, 'Вкусная Отрава', 'Балдеж!', 'Напиток', 'Харам');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (24, 'gorny_altai.png', 200, 'Барнаульский Эксклюзив', 'Bomba!', 'Напиток', 'Харам');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (25, 'orange_juice.png', 30, 'Стакан Счастья', '300 мл счастья', 'Напиток', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (26, 'tomato_juice.jpg', 30, 'Заморский Гость', 'Вот это да!', 'Напиток', 'Халяль');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (27, 'coca-cola.png', 100, 'Адский Кошмар', 'Не берите это', 'Напиток', 'Харам');
INSERT INTO shawarmas (id, filename, price, shawarma_title, description, category, morality) VALUES (28, 'dobry_cola.jpg', 10, 'Добрый Молодец', 'Русский дух!', 'Напиток', 'Халяль');